# zk configuration file

[notebook]
dir = "$ZK_NOTEBOOK_DIR"

[note]
filename = "{{id}}-{{slug title}}"
template = "default.md"
#extension = "md"
#id-charset = "alphanum"
#id-length = 4
#id-case = "lower"

[extra]

[format.markdown]
link-format = "wiki"
hashtags = true
colon-tags = false
multiword-tags = false

[tool]
fzf-preview = "bat -p --color always {-1}"
#editor = "vim"

[lsp]

[lsp.diagnostics]
wiki-title = "hint"
dead-link = "error"

[lsp.completion]

[filter]

[alias]
