# Key bindings for mpv

l seek 2 exact
L seek 10
h seek -2 exact
H seek -10

q quit
m cycle mute
t cycle ontop
SPACE cycle pause

k add volume +5
j add volume -5

> set speed 2.0
< set speed 1.0

# Resize mpv window
J add window-scale -0.2
K add window-scale +0.2

# Audio sync adjustment
A add audio-delay  0.1
a add audio-delay -0.1
